Left sidebar cleanup
CMSgov/regulations-site pull request #34
Opened 2021-04-29 18:22 UTC by inkandsound

2021-05-12 13:47 UTC, whytheplatypus requested changes

2021-05-12 13:47 UTC, whytheplatypus commented on regulations/templates/regulations/partials/toc_subpart.html
> +                <span tabindex="0" data-state="{{ collapse_state }}" data-set-state="expanded" data-state-name="{{item.type}}-{{item.identifier.0}}"><i class="fa fa-chevron-down"></i></span>
move these to `button`s for accessibility

2021-05-12 19:28 UTC, cgodwin1 commented
Note that 3886be9 includes adding links to subparts in the TOC

2021-05-18 17:04 UTC, whytheplatypus approved these changes

2021-05-18 18:54 UTC, merged