EREGCSC-607 EREGCSC-632 Regtext styling
CMSgov/regulations-site pull request #43
Opened 2021-05-20 14:02 UTC by whytheplatypus

edge cases: 
- [ ] paragraphs of the form (b)(1)

2021-05-24 18:30 UTC, whytheplatypus commented
https://vxfdykx862.execute-api.us-east-1.amazonaws.com/dev-regtext-styling-may/433/Subpart-A/2020-11-06/

2021-05-24 19:52 UTC, inkandsound commented on regulations/static/regulations/css/scss/partials/_reg_text.scss
> +                padding-left: $spacer-3 + $spacer-3 * ($i - 2);
I know I ended up changing this from `$spacer-3 + 16px` to conform to the design system stuff, but we could actually just write this as `$spacer-6` now that I look at it.

2021-05-24 19:57 UTC, inkandsound commented
@whytheplatypus The code looks good. There's a small alignment issue when the paragraphs don't have citations like (a) in front of them though - they're indented a bit too much and getting `depth-3` when they should be `depth-1`:

https://vxfdykx862.execute-api.us-east-1.amazonaws.com/dev-regtext-styling-may/433/Subpart-A/2020-11-06/#433-32

Compare to eCFR: https://www.ecfr.gov/cgi-bin/text-idx?node=pt42.4.433&rgn=div5#se42.4.433_132

Everything else looks good to me! We may want to get Rebecca to take a look.

2021-05-25 17:38 UTC, cgodwin1 approved these changes

2021-05-25 18:26 UTC, whytheplatypus commented on regulations/templates/regulations/partials/SECTION.html
> +<section id="{{c.label | join:'-'}}" class="reg-section depth-{{c.label|length}}">
sections don't need `depth-`

2021-05-25 18:27 UTC, whytheplatypus commented on regulations/templates/regulations/partials/SECTION.html
> +            {% render_nested "regulations/partials/"|add:node.node_type|add:".html" "regulations/partials/regulation_text.html" c=node first="false" %}
can update children templates to use the node as the context

2021-05-25 18:27 UTC, theabrad requested changes

2021-05-25 18:27 UTC, theabrad commented on regulations/templates/regulations/partials/SECTION.html
> +{% load render_nested %}
should be placed in subfolder for node_types

2021-05-25 18:27 UTC, theabrad commented on regulations/templates/regulations/partials/Paragraph.html
> +{% load paragraphs %}
Placed in sub folder node_types

2021-05-25 18:27 UTC, theabrad commented on regulations/templates/regulations/partials/Citation.html
> +{% load citation %}
Should be placed in node types subfolder

2021-05-27 17:41 UTC, cgodwin1 approved these changes

2021-05-27 19:38 UTC, merged