Removed PartialSectionView
CMSgov/regulations-site pull request #5
Opened 2021-01-22 15:35 UTC by theabrad

2021-01-26 18:38 UTC, whytheplatypus requested changes

2021-01-26 18:38 UTC, whytheplatypus commented on regulations/urls.py
> -        lt_cache(PartialSectionView.as_view()), name='partial_section_view'),
Now that these aren't being used, what else can be removed that would have called it? And can `PartialSectionView` and `PartialParagraphView` now be removed?

2021-02-04 20:04 UTC, cgodwin1 approved these changes

2021-02-05 15:48 UTC, whytheplatypus approved these changes

2021-02-05 15:53 UTC, merged